# Generated by Django 3.1 on 2020-10-01 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201001_1116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['-pk']},
        ),
    ]
